import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'dotenv';
import { z } from 'zod';

const currentFilePath = fileURLToPath(import.meta.url);
const projectRoot = resolve(dirname(currentFilePath), '..');
const envFilePath = resolve(projectRoot, '.env');
const proxyConfigPath = resolve(projectRoot, 'proxy.conf.json');
const environmentsDirectory = resolve(projectRoot, 'src/environments');

const defaultBackendUrl = 'http://localhost:5000/api';

const envSchema = z.object({
  BACKEND_URL: z
    .string()
    .trim()
    .url('BACKEND_URL debe ser una URL valida, por ejemplo http://localhost:5000/api')
});

const pathHasApiPrefix = (path) => /^\/api(?:\/|$)/.test(path);

const removeTrailingSlash = (value) => value.replace(/\/+$/, '');

const readFileIfExists = async (filePath) => {
  try {
    await access(filePath, fsConstants.F_OK);
    return await readFile(filePath);
  } catch {
    return null;
  }
};

const envBuffer = await readFileIfExists(envFilePath);

const envContent = envBuffer
  ? envBuffer[0] === 0xff && envBuffer[1] === 0xfe
    ? envBuffer.toString('utf16le')
    : envBuffer.toString('utf8')
  : '';

const fileEnv = envContent ? parse(envContent.replace(/^\uFEFF/, '')) : {};

const parsedEnv = envSchema.parse({
  BACKEND_URL: defaultBackendUrl,
  ...process.env,
  ...fileEnv
});

const backendUrl = removeTrailingSlash(parsedEnv.BACKEND_URL);
const backend = new URL(backendUrl);

const backendOrigin = `${backend.protocol}//${backend.host}`;
const backendPathname = removeTrailingSlash(backend.pathname || '');
const backendWithApiPath = pathHasApiPrefix(backendPathname)
  ? backendUrl
  : `${backendOrigin}/api`;

const buildEnvironmentFile = (production) => `// Auto-generated by scripts/sync-env.mjs
// Do not edit this file manually; update .env instead.
export const environment = {
  production: ${production},
  apiUrl: ${JSON.stringify(production ? backendWithApiPath : backendWithApiPath)}
} as const;
`;

await mkdir(environmentsDirectory, { recursive: true });

await Promise.all([
  writeFile(resolve(environmentsDirectory, 'environment.ts'), buildEnvironmentFile(true), 'utf8'),
  writeFile(
    resolve(environmentsDirectory, 'environment.development.ts'),
    buildEnvironmentFile(false),
    'utf8'
  ),
  writeFile(
    proxyConfigPath,
    JSON.stringify(
      {
        '/api': {
          target: backendOrigin,
          secure: false,
          changeOrigin: true,
          logLevel: 'info'
        }
      },
      null,
      2
    ),
    'utf8'
  )
]);

console.log(`Environment files synchronized with BACKEND_URL=${backendWithApiPath}`);
