import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'dotenv';
import { z } from 'zod';

const currentFilePath = fileURLToPath(import.meta.url);
const projectRoot = resolve(dirname(currentFilePath), '..');
const envFilePath = resolve(projectRoot, '.env');

const envSchema = z.object({
  BACKEND_URL: z
    .string()
    .trim()
    .url('BACKEND_URL debe ser una URL valida, por ejemplo http://localhost:3001')
});

const envBuffer = await readFile(envFilePath);
const envContent = envBuffer[0] === 0xff && envBuffer[1] === 0xfe
  ? envBuffer.toString('utf16le')
  : envBuffer.toString('utf8');

const fileEnv = parse(envContent.replace(/^\uFEFF/, ''));
const parsedEnv = envSchema.parse({ ...process.env, ...fileEnv });
const apiUrl = parsedEnv.BACKEND_URL.replace(/\/+$/, '');

const buildEnvironmentFile = (production) => `// Auto-generated by scripts/sync-env.mjs
// Do not edit this file manually; update .env instead.
export const environment = {
  production: ${production},
  apiUrl: ${JSON.stringify(production ? apiUrl : '/api')}
} as const;
`;

const environmentsDirectory = resolve(projectRoot, 'src/environments');
const proxyConfigPath = resolve(projectRoot, 'proxy.conf.json');

await mkdir(environmentsDirectory, { recursive: true });

await Promise.all([
  writeFile(resolve(environmentsDirectory, 'environment.ts'), buildEnvironmentFile(true), 'utf8'),
  writeFile(resolve(environmentsDirectory, 'environment.development.ts'), buildEnvironmentFile(false), 'utf8'),
  writeFile(
    proxyConfigPath,
    JSON.stringify(
      {
        '/api': {
          target: apiUrl,
          secure: false,
          changeOrigin: true,
          logLevel: 'info',
          pathRewrite: {
            '^/api': ''
          }
        }
      },
      null,
      2
    ),
    'utf8'
  )
]);

console.log(`Environment files synchronized with BACKEND_URL=${apiUrl}`);
